MOUSE_BUTTON_PRESSED = 0
MOUSE_BUTTON_RELEASED = 1

MOUSE_BUTTON_LEFT = 0
MOUSE_BUTTON_MIDDLE = 1
MOUSE_BUTTON_RIGHT = 2
MOUSE_WHEEL_UP = 3
MOUSE_WHEEL_DOWN = 4

MOUSE_STATE_NONE = 0
MOUSE_STATE_ROTATING = 1
MOUSE_STATE_TRANSLATING = 2
MOUSE_STATE_Z_ROTATING = 3
